apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: mongodb
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb
      project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: vasimphatan/mongodb:2.0.0
      

---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  
spec:
  selector:
    app: mongodb
    tier: mongodb
    project: roboshop
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
