apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop1
  labels: 
    app: catalogue
    tier: catalogue
    project: roboshop1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: catalogue
      project: roboshop1
  template:
    metadata:
      labels:
        app: catalogue
        tier: catalogue
        project: roboshop1
    spec:
      containers:
      - name: catalogue
        image: vasimphatan/catalogue:3.0.0
        envFrom:
        - configMapRef:
            name: catalogue

  
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop1

spec:
  selector:
    app: catalogue
    tier: catalogue
    project: roboshop1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop1
data:
  MONGO: "true"
    
  